function dimensionsEtiquetteDefaut() {
  return {
    largeurEtiquette: 75,
    hauteurEtiquette: 25,
  };
}

export const presets = {
  alice: {
    theme: "classique",
    modele: "alice",
    couleur1: "#942193",
    couleur2: "#ffffff",
    couleur3: "#ffffff",
    couleurRuban: "#ecdef6",
    couleurVignette: "#d9b6ee",
    couleurTitres: "#17120e",
    couleurArtiste: "#942193",
    decorPanel: "motif",
    angle: 0,
    intensite: 0,
    motifType: "aucun",
    couleurMotif: "#7c007c",
    motif: 45,
    angleMotif: 0,
    modeVignette: "fond",
    vignette: 0,
    bordure: 60,
    arrondiInterieurBordure: false,
    largeurRuban: 85,
    hauteurRuban: 25,
    hauteurBande: 15,
    policeTitres: "terminal-carre",
    policeArtiste: "luxe-fin",
    tailleTitres: 140,
    tailleArtiste: 150,
    styleTitres: "normal",
    styleArtiste: "gras",
    guillemetsTitres: true,
    afficherMarques: true,
    couleurMarques: "#ffffff",
    presetMarques: "custom",
    marqueGauche: "HIT",
    marqueDroite: "OLDY",
    policeMarques: "compacte",
    positionMarques: 6,
    hauteurMarques: 50,
    angleMarques: 0,
    tailleMarques: 155,
    limiterMarquesBandeSurprise: false,
    ...dimensionsEtiquetteDefaut(),
  },
  martin: {
    theme: "classique",
    modele: "martin",
    couleur1: "#0a4f95",
    couleur2: "#fffdf8",
    couleur3: "#fffdf8",
    couleurRuban: "#c8ddf8",
    couleurVignette: "#c8ddf8",
    couleurTitres: "#101923",
    couleurArtiste: "#084f95",
    decorPanel: "vignette",
    angle: 70,
    intensite: 80,
    motifType: "aucun",
    couleurMotif: "#0a4f95",
    motif: 45,
    angleMotif: 0,
    modeVignette: "fond",
    vignette: 80,
    bordure: 50,
    arrondiInterieurBordure: false,
    largeurRuban: 96,
    hauteurRuban: 25,
    hauteurBande: 0,
    afficherMarques: false,
    marqueGauche: "VINYL",
    marqueDroite: "CLUB",
    couleurMarques: "#ffffff",
    policeMarques: "compacte",
    positionMarques: 7.2,
    hauteurMarques: 50,
    angleMarques: -90,
    tailleMarques: 190,
    limiterMarquesBandeSurprise: false,
    policeTitres: "mono-moderne",
    policeArtiste: "elegante",
    tailleTitres: 110,
    tailleArtiste: 100,
    styleTitres: "gras",
    styleArtiste: "normal",
    guillemetsTitres: true,
    ...dimensionsEtiquetteDefaut(),
  },
  simple: {
    theme: "tout",
    modele: "simple",
    couleur1: "#d01b2b",
    couleur2: "#fffef7",
    couleur3: "#fffef7",
    couleurRuban: "#f1c2cd",
    couleurVignette: "#f1c2cd",
    couleurTitres: "#000000",
    couleurArtiste: "#d01c2a",
    decorPanel: "vignette",
    angle: 90,
    intensite: 100,
    motifType: "aucun",
    couleurMotif: "#d01b2b",
    motif: 0,
    angleMotif: 0,
    modeVignette: "fond",
    vignette: 80,
    bordure: 80,
    arrondiInterieurBordure: false,
    largeurRuban: 82,
    hauteurRuban: 25,
    hauteurBande: 2,
    afficherMarques: false,
    couleurMarques: "#ffffff",
    presetMarques: "custom",
    marqueGauche: "HIT",
    marqueDroite: "OLDY",
    policeMarques: "compacte",
    positionMarques: 6,
    hauteurMarques: 50,
    angleMarques: 0,
    tailleMarques: 155,
    limiterMarquesBandeSurprise: false,
    policeTitres: "dactylo-seche",
    policeArtiste: "elegante",
    tailleTitres: 170,
    tailleArtiste: 145,
    styleTitres: "normal",
    styleArtiste: "gras",
    guillemetsTitres: true,
    ...dimensionsEtiquetteDefaut(),
  },
  manu: {
    theme: "classique",
    modele: "manu",
    couleur1: "#111827",
    couleur2: "#ffffff",
    couleur3: "#ffffff",
    couleurRuban: "#ffffff",
    couleurVignette: "#000000",
    couleurFondModerne: "#000000",
    couleurBandeGauche: "#000000",
    couleurBandeDroite: "#000000",
    couleurTitres: "#111827",
    couleurArtiste: "#dc2626",
    decorPanel: "vignette",
    angle: 0,
    intensite: 0,
    motifType: "diagonales",
    couleurMotif: "#111827",
    motif: 20,
    angleMotif: 12,
    afficherTraitsModernes: false,
    motifTraitsModernes: "grille",
    couleurTraitsModernes: "#000000",
    opaciteTraitsModernes: 50,
    angleTraitsModernes: 0,
    modeVignette: "fond",
    vignette: 80,
    papierVieilli: false,
    couleurPapierVieilli: "#d9b6ee",
    jaunissementPapier: 50,
    froissagePapier: 30,
    imperfectionsPapier: 35,
    usureBordsPapier: 40,
    bordure: 33,
    arrondiInterieurBordure: true,
    largeurRuban: 62,
    hauteurRuban: 29,
    hauteurBande: 33,
    epaisseurTraitsLeon: 3,
    positionTraitsLeon: 50,
    ecartTraitsLeon: 24,
    tailleBandeGauche: 30,
    angleBandeGauche: 0,
    tailleBandeDroite: 30,
    angleBandeDroite: 0,
    afficherMarques: true,
    couleurMarques: "#dc2626",
    presetMarques: "45-o-juke",
    marqueGauche: "45’O",
    marqueDroite: "JUKE",
    policeMarques: "compacte",
    positionMarques: 8,
    hauteurMarques: 50,
    angleMarques: -25,
    tailleMarques: 180,
    formePastille: "losange",
    diametrePastille: 28,
    marqueGaucheTexte: "45’O",
    marqueDroiteTexte: "JUKE",
    couleurMarqueGauche: "#dc2626",
    couleurMarqueDroite: "#dc2626",
    formePastilleGauche: "losange",
    formePastilleDroite: "losange",
    policeMarqueGauche: "compacte",
    policeMarqueDroite: "compacte",
    styleMarqueGauche: "gras",
    styleMarqueDroite: "gras",
    tailleMarqueGauche: 180,
    tailleMarqueDroite: 180,
    diametrePastilleGauche: 28,
    diametrePastilleDroite: 28,
    angleMarqueGauche: -25,
    angleMarqueDroite: 25,
    positionMarqueGauche: 8,
    positionMarqueDroite: 8,
    hauteurMarqueGauche: 50,
    hauteurMarqueDroite: 50,
    limiterMarquesBandeSurprise: false,
    policeTitres: "dactylo-ronde",
    policeArtiste: "sans-serree",
    tailleTitres: 130,
    tailleArtiste: 150,
    styleTitres: "normal",
    styleArtiste: "gras",
    guillemetsTitres: true,
    ...dimensionsEtiquetteDefaut(),
  },
  celeste: {
    theme: "tout",
    modele: "celeste",
    couleur1: "#6d28d9",
    couleur2: "#e0f2fe",
    couleur3: "#fef08a",
    couleurRuban: "#fef08a",
    couleurVignette: "#f472b6",
    couleurFondModerne: "#ffffff",
    couleurBandeGauche: "#f472b6",
    couleurBandeDroite: "#6d28d9",
    couleurTitres: "#231033",
    couleurArtiste: "#3b1670",
    decorPanel: "motif",
    angle: 70,
    intensite: 90,
    motifType: "points",
    couleurMotif: "#6d28d9",
    motif: 22,
    angleMotif: 0,
    afficherTraitsModernes: false,
    motifTraitsModernes: "grille",
    couleurTraitsModernes: "#111827",
    opaciteTraitsModernes: 24,
    angleTraitsModernes: 28,
    modeVignette: "fond",
    vignette: 42,
    bordure: 79,
    arrondiInterieurBordure: false,
    largeurRuban: 71,
    hauteurRuban: 23,
    hauteurBande: 0,
    tailleBandeGauche: 8,
    angleBandeGauche: -35,
    tailleBandeDroite: 11,
    angleBandeDroite: -35,
    policeTitres: "dactylo-ronde",
    policeArtiste: "elegante",
    tailleTitres: 130,
    tailleArtiste: 115,
    styleTitres: "normal",
    styleArtiste: "gras",
    guillemetsTitres: true,
    afficherMarques: false,
    couleurMarques: "#fff7ff",
    presetMarques: "vinyl-select",
    marqueGauche: "VINYL",
    marqueDroite: "SELECT",
    policeMarques: "mono-moderne",
    positionMarques: 6,
    hauteurMarques: 50,
    angleMarques: -90,
    tailleMarques: 125,
    limiterMarquesBandeSurprise: false,
    ...dimensionsEtiquetteDefaut(),
  },
  leon: {
    theme: "classique",
    modele: "leon",
    couleur1: "#2a241c",
    couleur2: "#efe3c3",
    couleur3: "#efe3c3",
    couleurRuban: "#e3d6b3",
    couleurVignette: "#8a6b3f",
    couleurFondModerne: "#efe3c3",
    couleurBandeGauche: "#2a241c",
    couleurBandeDroite: "#2a241c",
    couleurTitres: "#19140f",
    couleurArtiste: "#485800",
    decorPanel: "papier",
    angle: 90,
    intensite: 42,
    motifType: "aucun",
    couleurMotif: "#7b623d",
    motif: 12,
    angleMotif: 0,
    afficherTraitsModernes: false,
    motifTraitsModernes: "grille",
    couleurTraitsModernes: "#7b623d",
    opaciteTraitsModernes: 10,
    angleTraitsModernes: 0,
    modeVignette: "aucun",
    vignette: 32,
    papierVieilli: true,
    couleurPapierVieilli: "#b28a52",
    jaunissementPapier: 0,
    froissagePapier: 50,
    imperfectionsPapier: 14,
    usureBordsPapier: 54,
    bordure: 0,
    arrondiInterieurBordure: false,
    largeurRuban: 0,
    hauteurRuban: 0,
    hauteurBande: 0,
    epaisseurTraitsLeon: 1.5,
    positionTraitsLeon: 50,
    ecartTraitsLeon: 24,
    tailleBandeGauche: 30,
    angleBandeGauche: 0,
    tailleBandeDroite: 30,
    angleBandeDroite: 0,
    margeArtisteJean: 28,
    policeTitres: "dactylo-seche",
    policeArtiste: "elegante",
    tailleTitres: 150,
    tailleArtiste: 90,
    styleTitres: "normal",
    styleArtiste: "gras",
    guillemetsTitres: true,
    afficherMarques: false,
    couleurMarques: "#2a241c",
    formePastille: "rond",
    diametrePastille: 33,
    presetMarques: "custom",
    synchroniserMarques: true,
    marqueGauche: "A",
    marqueDroite: "B",
    policeMarques: "compacte",
    marqueGaucheTexte: "HIT",
    marqueDroiteTexte: "OLDY",
    couleurMarqueGauche: "#2a241c",
    couleurMarqueDroite: "#2a241c",
    formePastilleGauche: "rond",
    formePastilleDroite: "rond",
    policeMarqueGauche: "compacte",
    policeMarqueDroite: "compacte",
    styleMarqueGauche: "gras",
    styleMarqueDroite: "gras",
    tailleMarqueGauche: 155,
    tailleMarqueDroite: 155,
    diametrePastilleGauche: 33,
    diametrePastilleDroite: 33,
    angleMarqueGauche: 0,
    angleMarqueDroite: 0,
    positionMarqueGauche: 6,
    positionMarqueDroite: 6,
    hauteurMarqueGauche: 50,
    hauteurMarqueDroite: 50,
    positionMarques: 6,
    hauteurMarques: 50,
    angleMarques: 0,
    tailleMarques: 155,
    limiterMarquesBandeSurprise: false,
    compositionJean: "centre",
    ...dimensionsEtiquetteDefaut(),
  },
};

export const combosSurprise = [
  {
    couleurs: ["#ff2f7d", "#1c1138", "#fff1a8", "#20d6d2", "#fff7ea", "#271439", "#fff7ea"],
    decor: "motif",
    motif: "diagonales",
    vignette: "global",
    marques: "stereo-sound",
  },
  {
    couleurs: ["#09215f", "#f9e3b2", "#ff6b35", "#152b6f", "#15120c", "#fff3da", "#ffef9a"],
    decor: "vignette",
    motif: "rayures",
    vignette: "fond",
    marques: "juke-box",
  },
  {
    couleurs: ["#0b7a75", "#fff7ec", "#f7cad0", "#f9d65c", "#13201f", "#832340", "#ffffff"],
    decor: "motif",
    motif: "points",
    vignette: "fond",
    marques: "music-box",
  },
  {
    couleurs: ["#d71920", "#fff6df", "#0f1115", "#f4c430", "#17120b", "#fff6df", "#ffffff"],
    decor: "vignette",
    motif: "grille",
    vignette: "global",
    marques: "old-hit",
  },
  {
    couleurs: ["#6d28d9", "#e0f2fe", "#fef08a", "#f472b6", "#231033", "#3b1670", "#fff7ff"],
    decor: "motif",
    motif: "rayures",
    vignette: "fond",
    marques: "vinyl-hit",
  },
  {
    couleurs: ["#0f5132", "#fffbe6", "#b7f7d4", "#d4a017", "#172016", "#064e3b", "#fff4c7"],
    decor: "vignette",
    motif: "diagonales",
    vignette: "fond",
    marques: "45-o-juke",
  },
  {
    couleurs: ["#004e89", "#fdf0d5", "#c1121f", "#7bdff2", "#111827", "#fff7ed", "#ffffff"],
    decor: "motif",
    motif: "grille",
    vignette: "global",
    marques: "hit-tune",
  },
  {
    couleurs: ["#121212", "#f8c8dc", "#b8f2e6", "#f15bb5", "#101010", "#101010", "#fffdf8"],
    decor: "vignette",
    motif: "points",
    vignette: "fond",
    marques: "a-side",
  },
  {
    couleurs: ["#ff7a00", "#2a0a3d", "#ffe45e", "#00c2ff", "#fff7e8", "#30104c", "#fff7e8"],
    decor: "motif",
    motif: "diagonales",
    vignette: "global",
    marques: "retro-hit",
  },
  {
    couleurs: ["#004643", "#abd1c6", "#f9bc60", "#e16162", "#001e1d", "#001e1d", "#fffffe"],
    decor: "motif",
    motif: "points",
    vignette: "global",
    marques: "vinyl-select",
  },
  {
    couleurs: ["#a4161a", "#f5f0e1", "#283618", "#dda15e", "#16120d", "#fff7e8", "#fffdf0"],
    decor: "vignette",
    motif: "rayures",
    vignette: "fond",
    marques: "aucun",
  },
];

export const palettesVariantesModernes = [
  {
    cadre: "#0f172a",
    fond: "#f8fafc",
    ruban: "#38bdf8",
    gauche: "#f59e0b",
    droite: "#be185d",
    motif: "#2563eb",
    secondaire: "#0f766e",
    vignette: "#6366f1",
  },
  {
    cadre: "#7f1d1d",
    fond: "#fff7ed",
    ruban: "#fed7aa",
    gauche: "#dc2626",
    droite: "#ea580c",
    motif: "#9a3412",
    secondaire: "#7c2d12",
    vignette: "#f97316",
  },
  {
    cadre: "#064e3b",
    fond: "#ecfdf5",
    ruban: "#a7f3d0",
    gauche: "#0f766e",
    droite: "#65a30d",
    motif: "#047857",
    secondaire: "#14532d",
    vignette: "#10b981",
  },
  {
    cadre: "#312e81",
    fond: "#eef2ff",
    ruban: "#c4b5fd",
    gauche: "#4338ca",
    droite: "#a21caf",
    motif: "#6366f1",
    secondaire: "#6d28d9",
    vignette: "#8b5cf6",
  },
  {
    cadre: "#111827",
    fond: "#fef3c7",
    ruban: "#fde68a",
    gauche: "#b45309",
    droite: "#92400e",
    motif: "#78350f",
    secondaire: "#451a03",
    vignette: "#f59e0b",
  },
  {
    cadre: "#0f172a",
    fond: "#111827",
    ruban: "#334155",
    gauche: "#0891b2",
    droite: "#4f46e5",
    motif: "#67e8f9",
    secondaire: "#a5b4fc",
    vignette: "#0ea5e9",
  },
];

export const modelesParTheme = {
  tout: [
    ["alice", "ALICE"],
    ["martin", "MARTIN"],
    ["simple", "JUJU"],
    ["manu", "MANU"],
    ["celeste", "CELESTE"],
    ["leon", "LEON"],
  ],
  classique: [
    ["alice", "ALICE"],
    ["martin", "MARTIN"],
    ["simple", "JUJU"],
    ["manu", "MANU"],
    ["leon", "LEON"],
  ],
  moderne: [
    ["celeste", "CELESTE"],
  ],
};

export const themesModeles = {
  tout: "Tout",
  classique: "Classique",
  moderne: "Moderne",
};

export const capacitesModeles = {
  alice: {
    marques: true,
    ruban: true,
    bandeCentrale: true,
  },
  martin: {
    marques: true,
    ruban: true,
    bandeCentrale: true,
  },
  simple: {
    marques: true,
    ruban: true,
    bandeCentrale: true,
  },
  manu: {
    marques: true,
    ruban: true,
    bandeCentrale: true,
  },
  celeste: {
    marques: true,
    ruban: true,
    bandeCentrale: false,
  },
  leon: {
    marques: false,
    ruban: false,
    bandeCentrale: false,
  },
};

export const presetsMarques = {
  custom: null,
  "juke-box": ["JUKE", "BOX"],
  "vinyl-hit": ["VINYL", "HIT"],
  "45-rpm": ["45", "RPM"],
  "hit-tune": ["HIT", "TUNE"],
  "old-hit": ["OLD", "HIT"],
  "top-side": ["TOP", "SIDE"],
  "a-side": ["A", "SIDE"],
  "b-side": ["B", "SIDE"],
  "stereo-sound": ["STEREO", "SOUND"],
  "vintage-label": ["VINTAGE", "LABEL"],
  "music-select": ["MUSIC", "SELECT"],
  "45-o-juke": ["45’O", "JUKE"],
  "juke-time": ["JUKE", "TIME"],
  "vinyl-side": ["VINYL", "SIDE"],
  "retro-hit": ["RETRO", "HIT"],
  "hit-parade": ["HIT", "PARADE"],
  "oldies-club": ["OLDIES", "CLUB"],
  "dance-tune": ["DANCE", "TUNE"],
  "music-box": ["MUSIC", "BOX"],
  "select-play": ["SELECT", "PLAY"],
  "side-one": ["SIDE", "ONE"],
  "side-two": ["SIDE", "TWO"],
  "top-vinyl": ["TOP", "VINYL"],
  "golden-hit": ["GOLDEN", "HIT"],
  "45-record": ["45", "RECORD"],
  "play-music": ["PLAY", "MUSIC"],
  "jukebox-sound": ["JUKEBOX", "SOUND"],
  "retro-label": ["RETRO", "LABEL"],
  "tune-select": ["TUNE", "SELECT"],
  "sound-track": ["SOUND", "TRACK"],
  "hit-record": ["HIT", "RECORD"],
  "vinyl-select": ["VINYL", "SELECT"],
};
